### ISSUE TITLE
What do we need for this ?

### ISSUE THREAD

**Issue by Karyum** [FACN3/Water-you-talking-about#11]
So to start this off we need to have a clear picture of what needs to  be done or gathered for this app.

For example we need to investigate how much a liter/cup of water, how much water an average tap would use per minute, how much the toilet use water after every flush i know this sounds a bit ridiculous, but again to have a clear picture of what you want to build. 

comment and update this issue on everything that you need **other than code**, i'll go through the prototype and try figure out what we need to research. but in the meanwhile can you guys @Amirk390 @SamiSha99 list what you might need for this app to work other than code ( use the example at the top as reference ).

So go research and comment your results for what you found out.

**Comment by Amirk390** [comment]
### Prices and usage:
+ Average costs for every Cubic Meters is 8.92 ₪
+ 1 Cubic Meters = 1,000 liters
  + Therefor 1,000 liters = 8.92 ₪

#### Average daily usage:
+ Shower: 65 liters (8.2 mins)
+ Faucet tap: 18.6 liters
+ Washing machine: 6.5 liters
+ Dishwasher 4 liters
+ Flushing: 4.5 small flush, 6 big flush

#### As a side notes:
+ Average person use in average 101 liter a day
+ an average person flush the toilet around 5 times a day

**Comment by Karyum** [comment]
@Amirk390 brabing barabong that's all we need right now for an MVP nothing more that's perfect.
There is nothing to worry about for data cause we got it all here with your comment. 

Hmmm also i was thinking since this is an MVP we don't need that graph that is on the prototype by that i mean we don't need an actualy one, a picture would be enough for now and if we have more time we would make like live or some shiz like that.

Ok great that's 1 thing less off of our chests, we got data! now we just need to use it!

**Comment by Amirk390** [comment]
@Karyum @SamiSha99 
> Ok great that's 1 thing less off of our chests, we got data! now we just need to use it!

Good! so our next goal is make some kind of a liter to cost convertor so:

+ 112 liter = **1 ₪**
+ 1 liter = **0.0089  ₪**

### Prices per activity 

 :moneybag: Shower: 45 liters = **0.4005 ₪**
 :moneybag: Faucet tap: 18.6 liters = **0.16554 ₪**
 :moneybag: Washing machine: 6.5 liters = **0.05785  ₪**
 :moneybag: Dishwasher 4 liters = **0.0356  ₪**
 :moneybag: Flushing: 4.5 small flush, 6 big flush = **0.04005 ₪** or **0.0534 ₪**
