### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Karyum** [FACN3/Water-you-talking-about#13]
+ [ ] Add All the water puns to the  README!!!
+ [x] Add ProtoType images and links

**Comment by Amirk390** [comment]
![calculator](https://user-images.githubusercontent.com/24490876/35803983-846a0468-0a7e-11e8-9b37-d00265775367.png)
![prices](https://user-images.githubusercontent.com/24490876/35803984-848d2ea2-0a7e-11e8-8962-71bc4fea2874.png)

**Comment by Amirk390** [comment]
@Karyum should we close this?
