### ISSUE TITLE
Tasks for today

### ISSUE THREAD

**Issue by Karyum** [FACN3/Water-you-talking-about#18]
@SamiSha99 
- [x] Investigate and test a basic calculating module
- [x] styled-components

@Amirk390 
- [x] [Change the README a bit to include user stories and your solution with some pics of the prototype.](https://github.com/FACN3/Water-you-talking-about/pull/22)
- [x] styled components. 
- [x] [Check more on React, build a basic counter. + and - with the value on the page](https://github.com/FACN3/Water-you-talking-about/issues/18#issuecomment-363110741)

**Comment by Amirk390** [comment]
@Karyum 

> Check more on React, build a basic counter. + and - with the value on the page

```js
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    }
    this.onClick = this.onClick.bind(this)
    
  }
  onClick(event){
    if(event.target.id){
       this.setState({count: this.state.count + 1});
    }else{
       this.setState({count: this.state.count - 1});
    }
  }
 
  render() {
    return (
    <div>
      <h1>Count: {this.state.count}</h1>
      <button id="up" onClick={this.onClick}>Count up</button>
      <button onClick={this.onClick}>Count down</button>
    </div>
     )
  }
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
);


```

**Comment by Karyum** [comment]
Good job guys!
