### ISSUE TITLE
List of daily activity 

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#24]
### What should we list as a daily activity in our website?

***Example of what im refering to:***
+ [Calculator](https://github.com/FACN3/Water-you-talking-about#calculator)
+ [List of prices](https://github.com/FACN3/Water-you-talking-about#specific-activity-prices)

***List of the current daily activity:***

+ Showers
+ Washing hands
+ Flushing the toilet
+ Filling a bottle of water
+ Filling a glass of water
+ Garden pipe of water

**Comment by Amirk390** [comment]
By what I understand.

We should avoid listing the small activity's and keep the bigger ones?

I.E: Showers, car washes etc?

**Comment by Amiraarraf** [comment]
How many activities can we include in the list?

**Comment by Amirk390** [comment]
@Amiraarraf 
> How many activities can we include in the list?

We can add as many as you would like 

In my opinion, we can just make a scroll down page with 3 icons in a row

**Comment by Amirk390** [comment]
@Karyum I'm closing this issue for now,

If more daily activity is needed we can discuss this in our next meeting
