### ISSUE TITLE
Navigator bar icons

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#27]
After speaking with king,

a good idea is to change the navigator mobile version to icons instead of words

**Comment by Karyum** [comment]
@Amirk390  is there a good reason for it ?

**Comment by Amirk390** [comment]
@Karyum 
> there a good reason for it ?

Yeah, i want t to be more simplistic in the mobile version so people won't struggle too much 

Examples


Twitter

<img src="https://user-images.githubusercontent.com/24490876/36071604-4399c8ac-0f19-11e8-8cac-774b6694b790.png" width="350">

Watsapp

![image](https://user-images.githubusercontent.com/24490876/36071613-6e29551a-0f19-11e8-8deb-070413bf41bc.png)

**Comment by Karyum** [comment]
@Amirk390 this should be more of question towards the PO, next time we have a meeting with her, we will add this topic to the agenda
