### ISSUE TITLE
Creating a footer

### ISSUE THREAD

**Issue by SamiSha99** [FACN3/Water-you-talking-about#28]
I just thought of this pretty quick, we need to create a footer.jsx file that renders bottom part information, it can be found in any site you go to so why not do that here too?

**Comment by Karyum** [comment]
@SamiSha99 you can't just start creating ideas on your own, this is not how it works the client requests something you build a design for it, if the client approves it then you build the website exactly how it looks on the design.
if developers have right to add whatever they want to the websites the they are working on it's going to be a frikin disaster.

So again if it exists on the design that you guys made and client approve then fine, if it doesn't then close this issue
