### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by Karyum** [FACN3/Water-you-talking-about#32]
We are not going to do a massive amount of tests it's mainly for the calculator logic all that we need to do is: 

- [x] Connect travis with our repo so it woud run on every PR
- [x] install tape and create a basic test in a folder called tests 
- [x] run the tests in the pre commit

PS : this might involve creating a file called travis.yml so you could run travis on github check it out `travis.yml`

**Comment by SamiSha99** [comment]
should I add `travis.yml` to my data branch?? @Karyum

**Comment by Karyum** [comment]
# NO
this is a different issue that means different pull request

**Comment by SamiSha99** [comment]
Should we close this?
