### ISSUE TITLE
Question about the design of the home page

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#34]
Hello @Amiraarraf ,

I would like to know how do you want the home page to look?

i have 2 different version of designs:

# Version 1
### Desktop 
![homepage2](https://user-images.githubusercontent.com/24490876/36092030-967ff2dc-0fee-11e8-884a-968f809d5005.png)

### Mobile
![homepagemobile2](https://user-images.githubusercontent.com/24490876/36092954-d562c008-0ff1-11e8-847f-aba46462af63.png)

# Version 2 

### Desktp

![homepage1](https://user-images.githubusercontent.com/24490876/36092031-96a4a186-0fee-11e8-88dd-2f08202b12d4.png)

### Mobile

![homepagemobile](https://user-images.githubusercontent.com/24490876/36092078-c3688f2a-0fee-11e8-97b4-c365a7f82050.png)

**Comment by Amiraarraf** [comment]
We would prefer version 1.

**Comment by Amirk390** [comment]
Ok sounds good
We will stick to version 1 design :smile:

**Comment by Amiraarraf** [comment]
Let me know if you need any information on the cost of different activities...

**Comment by Amirk390** [comment]
> Let me know if you need any information on the cost of different activities...

Oh yeah, we are planning to add soon enough shower time (with minutes) and time of flushing the toilet

We are using this information for now:  
https://github.com/FACN3/Water-you-talking-about/issues/11#issuecomment-363009184

if you have some more precise information this would be great :smile:

**Comment by Amiraarraf** [comment]
I requested the full information from the water corporation last week but unfortunately haven’t get it yet. Will try my best tomorrow to receive it.

**Comment by Amiraarraf** [comment]
Hi again, 
Around 13:00 PM i will get all the precise information from the Corporation for Water, will it still be actual?

**Comment by Amirk390** [comment]
@Amiraarraf 
> Hi again,
> Around 13:00 PM i will get all the precise information from the Corporation for Water, will it still be actual?

Sounds great, thanks :smile: :tada:
