### ISSUE TITLE
Any idea's how we can uploade image using webpack?

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#38]
@Karyum @SamiSha99 

So I'm trying to upload an image so it will work as an icon in the ***[Calculator Page](https://github.com/FACN3/Water-you-talking-about#calculator)***

i tried already usin
```
const Icon = styled.img``;

<Icon src="path-of-file">
```
but it doesnt seems to work.. 
any ideas how we can do it in an efficient way?

**Comment by Karyum** [comment]
@Amirk390 did you find out how ?

**Comment by SamiSha99** [comment]
It has been fixed, we should close this @Karyum

**Comment by Karyum** [comment]
yeah but what did you change for it to work?

**Comment by Amirk390** [comment]
## We did the next steps:

1. We added this to the *webpack.config.js*
```
  module: {
    loaders: [
      {
        test: /\.png$/,
        loader: 'file-loader?name=[name].[ext]',
      },
    ],
  },
```

2. Made a file that imports all of our images 

```
import '../../assets/bottle.png';
import '../../assets/calculator.png';
import '../../assets/flush.png';
import '../../assets/glass.png';
import '../../assets/plumbing-pipe.png';
import '../../assets/shower.png';
import '../../assets/statics.png';
import '../../assets/videos.png';
import '../../assets/washing-hands.png';

```

3. we imported the file that import the images `import './styles/images'`

4. run the command `npm run build` (so it will make some encoded version of our image)

5. we addressed the encoded version of our images in the /dist folder
  `src="/washing-hands.png"`
