### ISSUE TITLE
calculating price for each activity  

### ISSUE THREAD

**Issue by SamiSha99** [FACN3/Water-you-talking-about#4]
# User Story:

As a Water consumer, 
I want to choose a certain activity and know how much water being used also how much money :dollar: 
So that I would be more careful with using Water.

# Acceptance criteria

- [x] Making a Price Page
- [ ] [Giving the user the ability to insert specific information and not the provided one (Cup and half, 36 minutes and 40 seconds in a shower etc)](https://github.com/FACN3/washinator/issues/9)

**Comment by Amirk390** [comment]
# DONE 
### @Karyum @matthewdking 
Thanks guys for the patient and the help you provided us! :clap: 
![](https://i0.wp.com/sendtask.io/wp-content/uploads/2017/04/emoji-tada.png?ssl=1)
