### ISSUE TITLE
Deploy website to production

### ISSUE THREAD

**Issue by Karyum** [FACN3/Water-you-talking-about#43]
We have a static website, we don't have a backend so we don't need Heroku to deploy the website.
we also have the following options:
- [Surge](http://surge.sh/)
- [Github pages](https://pages.github.com/)
- [Netlify](https://www.netlify.com/?gclid=EAIaIQobChMIv862y_an2QIVReAYCh2z7g-_EAAYASAAEgI15PD_BwE) (looks interesting and easy to deploy)

**Comment by Amirk390** [comment]
I like those 2 options

- [Github pages](https://pages.github.com/)
- [Netlify](https://www.netlify.com/?gclid=EAIaIQobChMIv862y_an2QIVReAYCh2z7g-_EAAYASAAEgI15PD_BwE)

**Comment by Karyum** [comment]
@SamiSha99 is on it. can you send the website's url ??

**Comment by Karyum** [comment]
it was hosted by @SamiSha99 to Netlify on https://water-you-talking-about.netlify.com/
