### ISSUE TITLE
Water you talking about - Demo

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#44]
Hey @Amiraarraf ,

We would like to hear your opinion about our results till now,

The website still in progress and not yet fully functional, this is originally created for mobile, but it's also compatible with desktop too and other devices.

**Website link:** https://water-you-talking-about.netlify.com/

*we will contact you again when the website is fully functional*

**Comment by Amiraarraf** [comment]
It looks lovely and user friendly. 
I will show it on next sunday to my colleagues and let you know their feedback. 

Have a nice weekend all
