### ISSUE TITLE
Nav bar styling and animation

### ISSUE THREAD

**Issue by matthewdking** [FACN3/Water-you-talking-about#45]
Currently when you click the nav bar to get the dropdown it pushes all other content down. I don't think this is ideal functionality and it behaves differently in your prototype.

**Comment by SamiSha99** [comment]
Well since the navbar closes itself automatically when it changes to another domain, I think it is safe to make the position of the navbar fixed.

**Comment by Amirk390** [comment]
Good point, 

i marked it as priority 4 and hopefully if we will have enough time, we will fix it 
---
EDIT:
i created an issue that address bunch of style issues 
#48
