### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#58]
So, we finished all the demo pages :tada: 

We should now spend the time fixing all the minor bugs

Please list ANY big or small issue you found in our website below

### List:
- [x] Prices page buttons doesnt have `cursor: point;`
- [x] Minutes in calculator page [doesnt fit all mobile versions](https://github.com/FACN3/Water-you-talking-about/issues/58#issuecomment-367254961)
- [x] page being pushed to the side in mobile version
- [x] dropdown menu was outside of the website frame in mobile versions

**Comment by SamiSha99** [comment]
We should probably adjust text in the Calculator page for the buttons with minutes in it.

Huawei 2017 lite

Pic https://cdn.discordapp.com/attachments/326367632582508544/415793058681061377/Screenshot_20180221-105203.png
