### ISSUE TITLE
Creating calculator component

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Water-you-talking-about#7]
a component that renders  the activities with their symbols/icons with their own styling and own **onClick function** ( if it's a time or amount, but if we are doing by 1 minutes and 1 times for each click then the event listeners functions should be the same ).

also this component has a `Calculate` button which calculates what the user has chosen with the data that we have using the calculate module #14 , and renders back the overall cost and overall liters.

### Work need to be done:

- [x] Functionality 
   - [x] Clickable icons
   - [x] Stacking +1 Functionality
   - [x] Working Calculator (X Liters = x Shekels)
    - [x] :point_right:  The calculator should reset everything :point_left: :exclamation:

- [x] Design 
  - [X] Icons
  - [x] Dekstop Design
  - [x] Mobile Design
  - [x] Calculate Button

**Comment by Amirk390** [comment]
Updated the issue message so it will meet this:

@Karyum 
> @matthewdking yeah good poing we should split the issues into styling/html and functionality.
> 
> @Amirk390 or @SamiSha99 can you please sort this out by specifying in the issue the we split the two and make checkboxes for them

**Comment by SamiSha99** [comment]
We need to make sure to create an object that holds all the data of how much the user clicked for each indiviual button, after pressing calculate, this data goes into the calculator logic and releases, cost and liters and should be sent back to the calculator page and revealed to the user.
